language: go

stages:
  - name: after_success
    if: tag IS blank

go:
  - "1.10"

before_script:
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

script:
    - make test

after_success:
  - $GOPATH/bin/overalls -project=github.com/italolelis/reachable -covermode=count -debug
  - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
